eval $(ssh-agent) &> /dev/null
ssh-add /root/.ssh/id_rsa &> /dev/null

cat <<EOF
Welcome to Big(O) test script on Docker
===========================

This container runs the jepsen tests in sub-containers.

You are currently in the base dir of the git repo for Big(O).
If you modify the core jepsen library make sure you "lein install" it so other tests can access.

To run a test:
   lein run test --concurrency 10
EOF

cd /jecci
